[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = { version = "0.4", features = ["headers"] }
include_dir = "0"
tokio = { version = "1", features = ["full"] }
tracing = "0"
tracing-subscriber = "0"
